api:
  id: "123"
  listener:
    path: "/*"

http:
  listener:
    host: "0.0.0.0"
    port: "8091" 
    
    
sf-orders-sapi:
  host: "0.0.0.0"
  protocol: "HTTP"
  port: "8083"
  basePath: ""
  
csv-orders-sapi:
  host: "0.0.0.0"
  protocol: "HTTP"
  port: "8084"
  basePath: ""