api:
  id: "19990330"
  listener:
    path: "/*"
http:
  listener:
    host: "0.0.0.0"
    port: "8081" 
    
sapi-orders-sf:
  host: "sapi-orders-sf.us-e2.cloudhub.io"
  protocol: "HTTP"
  port: "8081"
  basePath: "/api"
  
  
sapi-orders-adhetec:
  host: "sapi-orders-adhetec.us-e2.cloudhub.io"
  protocol: "HTTP"
  port: "8081"
  basePath: "/api"